version: 1.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/IV.EFLC.ColAccel.sln
  verbosity: minimal
before_package:
- cmd: >-
    cd data

    release.bat
artifacts:
- path: data/IV.EFLC.ColAccel.zip
  name: IV.EFLC.ColAccel.zip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: IV.EFLC.ColAccel v$(appveyor_build_version)
  description: "[GTAForums original topic](http://gtaforums.com/topic/676844-colaccel-reduce-loading-time-by-50/) \xD83C\xDF42\xD83C\xDF42\xD83C\xDF42\xD83C\xDF42\\n"
  auth_token:
    secure: SXMI7bm5RKh5j1S8A8dnUP2HFw97xHHlJH+mA0hx819vtxOPCpMFY3aFZ+2v16ri
  artifact: IV.EFLC.ColAccel.zip